[[ main ]]
  name = "Home"
  url = "/"
  weight = 10

[[ main ]]
  name = "Groups"
  identifier = "group"
  weight = 50
  hasChildren = true

[[ main ]]
  name = "Core"
  parent = "group"
  url = "/core/"
  weight = 10

[[ main ]]
  name = "Supplementary"
  parent = "group"
  url = "/supplementary/"
  weight = 20

[[ main ]]
  name = "Intelligence"
  parent = "group"
  url = "/intelligence/"
  weight = 30