# SITE SETUP
# Documentation: https://sourcethemes.com/academic/

########################################################################################
## Theme
theme = "ucfai"
day_night = false  # need to properly setup night more before enabling

# Override the theme's font set (optional).
#   Latest font sets (may require updating): https://sourcethemes.com/academic/themes/
#   Browse built-in font sets in `themes/academic/data/fonts/`
#   Browse user installed font sets in `data/fonts/`
font = "Fira Sans"

# Choose a font size.
# Sizes: XS (extra small), S (small), M (medium), L (large - DEFAULT), XL (extra large)
font_size = "L"
########################################################################################

########################################################################################
## Basic Info
# Based on: https://schema.org/Organization#subtypes
site_type = "EducationalOrganization"
local_business_type = ""  # we're not a local business, so ignore this
org_name = "AI@UCF"
description = "We're forging UCF into a hotspot for researchers and engineers passionate about computational intelligence and data science."
########################################################################################

########################################################################################
## Site Features

### Highlighting
highlight = true
# what languages should we highlight?
highlight_languages = ["r", "python", "javascript"]
highlight_style = "github"  # For supported styles, see https://cdnjs.com/libraries/highlight.js/

### Fancy Maths/Diagrams
math = true  # Enable LaTeX math rendering? true/false
diagram = true  # Enable diagram rendering? true/false

# Privacy pack
#   Show a cookie consent message to visitors
#   Anonymize IP in Google Analytics (if enabled)
privacy_pack = false

# Enable visitors to edit pages?
edit_page = {repo_url = "https://github.com/ucfai/ucfai.org", content_dir = "content", repo_branch = "master", editable = {docs = true, page = false, post = false}}
########################################################################################

########################################################################################
## Contact details

email = "admins@ucfai.org"
phone = ""

address = {street = "450 Serra Mall", city = "Stanford", region = "CA", postcode = "94305", country = "United States", country_code = "US"}

# Geographic coordinates
coordinates = {latitude = "37.4275", longitude = "-122.1697"}

# Directions for visitors to locate you.
directions = "Enter Building 1 and take the stairs to Office 200 on Floor 2"

# Office hours
office_hours = []

# Enter an optional link for booking appointments (e.g. calendly.com).
appointment_url = "https://calendly.com"

# Contact links
contact_links = []
########################################################################################

########################################################################################
## Social
# Default image for social sharing and search engines. Place image in `static/img/` folder and specify image name here.
sharing_image = ""

# Twitter username (without @). Used when a visitor shares your site on Twitter.
twitter = "ucfai"
########################################################################################

########################################################################################
## Regional Settings

# based on: https://sourcethemes.com/academic/docs/customization/#date-format
date_format = "Jan 2, 2006"
time_format = "3:04 PM"

address_format = "en-us"

########################################################################################
## Advanced
gravatar = false   # Get user avatars from Gravatar.com? (true/false)

# Main menu alignment (l = left, c = center, r = right) and logo options.
main_menu = {align = "l", show_logo = true}

# Show estimated reading time for posts? (true/false)
reading_time = true

# Display next/previous section pager? (true/false)
section_pager = true
docs_section_pager = true  # Display pager in Docs layout (e.g. tutorials)?

# Enable in-built social sharing buttons? (true/false)
sharing = true

# Link authors to their profile page? (true/false)
link_authors = true

# Load JS plugins
#   E.g. To load `/assets/js/custom.js`, set `plugins_js = ["custom"]`.
# plugins_js  = ["particles-config", "moment", "countdowntime"]
# plugins_css = ["authors"]

# Available address formats.
[address_formats]
  en-us = {order = ['street', 'city', 'region', 'postcode'], delimiters = [', ', ', ', ' ', '']}

# Configuration of publication pages.
[publications]
  # based on: https://sourcethemes.com/academic/docs/customization/#date-format
  date_format = "Jan 2006"
  citation_style = "apa"  # Citation style ("apa" or "mla")

# Configuration of project pages.
[projects]
  # Views for associated content.
  #   1: List
  #   2: Compact
  #   3: Card
  #   4: Citation (publications only)
  post_view = 2
  publication_view = 2
  talk_view = 2
########################################################################################

########################################################################################
## Comments
[comments]
  engine = 0  # direct questions to Discord, we don't need to moderate the site
  commentable = {}
########################################################################################

########################################################################################
## Search
[search]
  engine = 1  # use Academic's built-in search engine (unclear if Algolia is better)
########################################################################################

########################################################################################
## Maps
[map]
  engine = 0
########################################################################################

########################################################################################
## Marketing
[marketing]
  google_analytics = ""
  google_tag_manager = ""
########################################################################################
