version: "3.4"
services:
  hugo:
    image: jojomi/hugo:0.60.0
    container_name: hugo-ucfai-org
    environment:
      - HUGO_THEME="academic"
      - HUGO_WATCH=true
      # - HUGO_BASEURL=
    volumes:
      - .:/src
      # use the volume mount below to inspect the hugo output, IFF needed
      # - ./build:/output
    ports:
      - 8234:1313
