version: "3.4"
services:
  hugo:
    image: "klakegg/hugo:0.80.0-ext"
    container_name: ucfai-org
    command:
      - server  # from Dockerfile
      - --buildFuture
      - --disableFastRender
      - --verbose
    volumes:
      - .:/src
      # use the volume mount below to inspect the hugo output, IFF needed
      # - ./build:/output
    ports:
      - 8234:1313
