[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENABLEGITINFO = "true"

[context]

[context.production]

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
for = "*.webmanifest"

[headers.values]
Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
for = "index.xml"

[headers.values]
Content-Type = "application/rss+xml"

[[redirects]]
from = "/discord"
to = "https://discord.gg/7vwjC8P"
status = 301

[[redirects]]
from = "/discord/announcements"
to = "https://discord.com/channels/363524680851914752/363524782974828544"
status = 301

[[redirects]]
from = "/discord/gbms"
to = "https://discord.com/channels/363524680851914752/713337547044028436"
status = 301

[[redirects]]
from = "/discord/core"
to = "https://discord.com/channels/363524680851914752/496942430193582080"
status = 301

[[redirects]]
from = "/discord/discussions"
to = "https://discord.com/channels/363524680851914752/518898052182966297"
status = 301

[[redirects]]
from = "/discord/projects"
to = "https://discord.com/channels/363524680851914752/580142880564445244"
status = 301

[[redirects]]
from = "/google-calendar"
to = "https://calendar.google.com/calendar?cid=cXBwczcxZHNxcDRxNHN2MHYwaXZ2MTlxazRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ"
status = 301

[[redirects]]
from = "/calendar"
to = "https://calendar.google.com/calendar/embed?src=qpps71dsqp4q4sv0v0ivv19qk4%40group.calendar.google.com&ctz=America%2FNew_York"
status = 301

[[redirects]]
from = "/github"
to = "https://github.com/ucfai"
status = 301

[[redirects]]
from = "/kaggle"
to = "https://kaggle.com/ucfaibot"
status = 301

[[redirects]]
from = "/feedback"
to = "https://forms.gle/rzoTSH4LRgD3Wt5C6"
status = 301

[[redirects]]
from = "/signin"
to = "https://docs.google.com/forms/d/e/1FAIpQLSdl1QoqkJLAtHiVpP4dn-t3RMHu8bPpZG_2Hh3eUbwkITz38g/viewform"
status = 301

[[redirects]]
from = "/signup"
to = "https://docs.google.com/forms/d/e/1FAIpQLSejUfUuqBGQCExrcJcbPrPSQgcDfH4ebFzKlr6mKAONCQWk7w/viewform"
status = 301

[[redirects]]
from = "/facebook-page"
to = "https://facebook.com/ucfsigai"
status = 301

[[redirects]]
from = "/instagram"
to = "https://www.instagram.com/_ucfai"
status = 301

[[redirects]]
from = "/tshirts"
to = "https://docs.google.com/forms/d/e/1FAIpQLSd8_-Awm3ukHGytAWeKe3Ij3rRsKSgYW4m8_vygpw0hQ7jkIw/viewform"
status = 301

[[redirects]]
from = "/forms/acm-w"
to = "https://docs.google.com/forms/d/e/1FAIpQLSd_fb5auM59_0icRKDNmc3iV6j3V8ZksDaob1pi3T2cr8s8Hw/viewform"
status = 301

[[redirects]]
from = "/newsletter"
to = "https://mailchi.mp/77de8f0b3e18/sept2020-newsletter"
status = 301

[[redirects]]
from = "/interest-meeting"
to = "https://ucfai.org/groups/gbms/sp21/interest-meeting/"
status = 301

[[redirects]]
from = "/interest-meeting-pres"
to = "https://ucfai.org/groups/gbms/sp21/interest-meeting/"
status = 301

[[redirects]]
from = "/linktree"
to = "https://linktr.ee/ucfai"
status = 301

[[redirects]]
from = "/apply"
to = "https://forms.gle/WZJv9ttNH3W9pQtQ9"
status = 301

[[redirects]]
from = "/event-interest"
to = "https://forms.gle/8jYpJ29kK8TqdX8X7"
status = 301

[[redirects]]
from = "/gbm-meeting"
to = "https://ucf.zoom.us/j/98719091390"
status = 301

[[redirects]]
from = "/discussions-meeting"
to = "https://ucf.zoom.us/j/99073401370"
status = 301

[[redirects]]
from = "/projects-meeting"
to = "https://ucf.zoom.us/j/93823882013?pwd=ZC9MOTNVMXNwUnh2TlIrakZNS1VKZz09"
status = 301

[[redirects]]
from = "/subscribe-newsletter"
to = "http://eepurl.com/g9dlv1"
status = 301

[[redirects]]
from = "/youtube"
to = "https://www.youtube.com/channel/UCyokaec6yvsotHXFz9pbcaA"
status = 301
