[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENABLEGITINFO = "true"

[context]

[context.production]

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
for = "*.webmanifest"

[headers.values]
Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
for = "index.xml"

[headers.values]
Content-Type = "application/rss+xml"

[[redirects]]
from = "/calendar"
to = "https://calendar.google.com/calendar?cid=cXBwczcxZHNxcDRxNHN2MHYwaXZ2MTlxazRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ"
status = 301

[[redirects]]
from = "/github"
to = "https://github.com/ucfai"
status = 301

[[redirects]]
from = "/kaggle"
to = "https://kaggle.com/ucfaibot"
status = 301

[[redirects]]
from = "/feedback"
to = "https://docs.google.com/forms/d/e/1FAIpQLSdOZLuDIJebQ5bLHsghTxEBjm57Eb6Oe-qQ48WmTeFv7uBdEw/viewform"
status = 301

[[redirects]]
from = "/signin"
to = "https://docs.google.com/forms/d/e/1FAIpQLSdl1QoqkJLAtHiVpP4dn-t3RMHu8bPpZG_2Hh3eUbwkITz38g/viewform"
status = 301

[[redirects]]
from = "/facebook-page"
to = "https://facebook.com/ucfsigai"
status = 301

[[redirects]]
from = "/instagram"
to = "https://www.instagram.com/_ucfai"
status = 301

[[redirects]]
from = "/tshirts"
to = "https://docs.google.com/forms/d/e/1FAIpQLSd8_-Awm3ukHGytAWeKe3Ij3rRsKSgYW4m8_vygpw0hQ7jkIw/viewform"
status = 301

[[redirects]]
from = "/discord"
to = "https://discord.gg/7vwjC8P"
status = 301

[[redirects]]
from = "/discord/accouncements"
to = "https://discord.com/channels/363524680851914752/363524782974828544"
status = 301

[[redirects]]
from = "/discord/gbms"
to = "https://discord.com/channels/363524680851914752/713337547044028436"
status = 301

[[redirects]]
from = "/discord/core"
to = "https://discord.com/channels/363524680851914752/496942430193582080"
status = 301

[[redirects]]
from = "/discord/discussions"
to = "https://discord.com/channels/363524680851914752/518898052182966297"
status = 301

[[redirects]]
from = "/discord/projects"
to = "https://discord.com/channels/363524680851914752/580142880564445244"
status = 301
