[build]
command = "hugo --gc --minify -b $URL"
publish = "public"

[build.environment]
HUGO_VERSION = "0.73.0"
HUGO_ENABLEGITINFO = "true"

[context]

[context.production]

[context.production.environment]
HUGO_ENV = "production"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
command = "hugo --gc --minify -b $DEPLOY_PRIME_URL"

[[headers]]
for = "*.webmanifest"

[headers.values]
Content-Type = "application/manifest+json; charset=UTF-8"

[[headers]]
for = "index.xml"

[headers.values]
Content-Type = "application/rss+xml"

[[redirects]]
from = "/discord"
to = "https://discord.gg/7vwjC8P"
status = 301

[[redirects]]
from = "/admin-calendar"
to = "https://calendar.google.com/calendar/u/0?cid=aW9ubGlnaHRzLmNvbV8wZ2toZnJwdTJrcHMxZG03b3J1azhxZXVrc0Bncm91cC5jYWxlbmRhci5nb29nbGUuY29t"
status = 301

[[redirects]]
from = "/google-calendar"
to = "https://calendar.google.com/calendar?cid=cXBwczcxZHNxcDRxNHN2MHYwaXZ2MTlxazRAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ"
status = 301

[[redirects]]
from = "/calendar"
to = "https://calendar.google.com/calendar/embed?src=qpps71dsqp4q4sv0v0ivv19qk4%40group.calendar.google.com&ctz=America%2FNew_York"
status = 301

[[redirects]]
from = "/schedule"
to = "https://calendar.google.com/calendar/embed?src=qpps71dsqp4q4sv0v0ivv19qk4%40group.calendar.google.com&ctz=America%2FNew_York"
status = 301

[[redirects]]
from = "/tasks"
to = "https://keep.google.com/?note=17E6BR5refzPVCtz0xjCvXJgAVidEF2LlfPFSo_Q2BPepkWeX4elEdy9QkP0o4g&tid=true"
status = 301

[[redirects]]
from = "/github"
to = "https://github.com/ucfai"
status = 301

[[redirects]]
from = "/feedback"
to = "https://forms.gle/V9hjVGn5kBzjfWFu7"
status = 301

[[redirects]]
from = "/facebook"
to = "https://facebook.com/ucfsigai"
status = 301

[[redirects]]
from = "/instagram"
to = "https://www.instagram.com/_ucfai"
status = 301

[[redirects]]
from = "/kaggle"
to = "https://kaggle.com/ucfaibot"
status = 301

[[redirects]]
from = "/newsletter"
to = "https://us19.campaign-archive.com/home/?u=f1da4378398d0f3af136bfb7f&id=5a2c1d8a24"
status = 301

[[redirects]]
from = "/linktree"
to = "https://linktr.ee/ucfai"
status = 301

[[redirects]]
from = "/apply"
to = "https://forms.gle/WZJv9ttNH3W9pQtQ9"
status = 301

[[redirects]]
from = "/documentation"
to = "https://www.notion.so/ucfai/481486ee6ef84391bacfb68a760f9aff?v=13c996434d4143c689726b4e1417ba2a"
status = 301

[[redirects]]
from = "/youtube"
to = "https://www.youtube.com/channel/UCyokaec6yvsotHXFz9pbcaA"
status = 301

[[redirects]]
from = "/drive"
to = "https://drive.google.com/drive/folders/1vGyy2p8m7iUXxDK2ii8ZH2HUjoy6BRBp?usp=sharing"
status = 301

[[redirects]]
from = "/knightconnect"
to = "https://knightconnect.campuslabs.com/engage/organization/ucfai"
status = 301

[[redirects]]
from = "/signin"
to = "https://docs.google.com/forms/d/e/1FAIpQLSdl1QoqkJLAtHiVpP4dn-t3RMHu8bPpZG_2Hh3eUbwkITz38g/viewform"
status = 301

[[redirects]]
from = "/signup"
to = "https://docs.google.com/forms/d/e/1FAIpQLSejUfUuqBGQCExrcJcbPrPSQgcDfH4ebFzKlr6mKAONCQWk7w/viewform"
status = 301

[[redirects]]
from = "/promo-slide"
to = "https://docs.google.com/presentation/d/1O11hwpTto5Dp6VTSIPqoMDo00Aw-NX5FuFs1qevOXkk"
status = 301
