backend:
  name: github
  repo: ucfai/ucfai.org
  branch: release-hugo-academic-base
  use_graphql: true

publish_mode: editorial_workflow

media_folder: static/img
public_folder: /img

logo_url: https://ucfai.org/brand/fullmark/light-bg-ready.svg

collections:
  - name: "Coordinator"
    label: "Coordinators"
    folder: "content/authors/"
    path: "{{ slug }}/_index.md"
    create: true
    slug: "{{ fields.github }}"
    preview_path: "authors/{{ slug }}"
    format: "yaml-frontmatter"
    editor:
      preview: false
    fields:
      # Name
      - { widget: "string", label: "Name", name: "name" }
      # Title - this is req'd by Netlify CMS
      - { widget: "hidden", label: "Title", name: "title" }
      # GitHub account name
      - { widget: "string", label: "GitHub", name: "github" }
      # "ucfai.roles" and "ucfai.teams"
      - widget: "object"
        label: "Participation in AI@UCF"
        name: "ucfai"
        fields:
          - { widget: "select", label: "Role(s)", name: "roles", multiple: true, options: ["Founder", "President", "Director", "Coordinator", "Maintainer"], default: "Coordinator", hint: "These are all the roles you've had while in AI@UCF."}
          - widget: "list"
            label: "Academic Year(s)"
            name: "teams"
            hint: "What academic years have you been part of?"
            field: { widget: "date", label: "Academic Year", format: "YYYY", dateFormat: "YYYY" }
      - { widget: "string", label: "Role", name: "role", hint: "Briefly describe your role(s) this semester" }
      - { widget: "markdown", label: "Self-description", name: "body", hint: "Describe yourself. What are your interests? What sparked your desire to join the club? What are you doing outside of classes? What about after you graduate? etc." }