# https://ericjinks.com/blog/2019/netlify-scheduled-build/
# L2Crontab: https://crontab.guru/
name: Crontab Rebuilds

on:
  schedule:  # crontab times are in UTC
    - cron: "0 6,14,22 * * *" # daily at 01am, 09am, and 05pm EST

jobs:
  crontab-rebuild:
    name: Daily Rebuild (n of 3)
    runs-on: ubuntu-latest
    steps:
      - name: Ping the Build Hook
        run: curl -X POST -d {} ${{ secrets.netlify_hugo_webhook }}
